#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : krusader
Version  : 2.7.2
Release  : 1
URL      : https://github.com/KDE/krusader/archive/v2.7.2.tar.gz
Source0  : https://github.com/KDE/krusader/archive/v2.7.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: krusader-bin = %{version}-%{release}
Requires: krusader-data = %{version}-%{release}
Requires: krusader-lib = %{version}-%{release}
Requires: krusader-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde

%description
Krusader-2.7.2 "Peace of Mind"
=================================
Krusader is an advanced twin panel (commander style) file manager for KDE Plasma
and other desktops in the *nix world, similar to Midnight or Total Commander.

%package bin
Summary: bin components for the krusader package.
Group: Binaries
Requires: krusader-data = %{version}-%{release}

%description bin
bin components for the krusader package.


%package data
Summary: data components for the krusader package.
Group: Data

%description data
data components for the krusader package.


%package doc
Summary: doc components for the krusader package.
Group: Documentation
Requires: krusader-man = %{version}-%{release}

%description doc
doc components for the krusader package.


%package lib
Summary: lib components for the krusader package.
Group: Libraries
Requires: krusader-data = %{version}-%{release}

%description lib
lib components for the krusader package.


%package man
Summary: man components for the krusader package.
Group: Default

%description man
man components for the krusader package.


%prep
%setup -q -n krusader-2.7.2
cd %{_builddir}/krusader-2.7.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579984435
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1579984435
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/krusader

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.krusader.desktop
/usr/share/icons/hicolor/128x128/apps/krusader_root.png
/usr/share/icons/hicolor/128x128/apps/krusader_user.png
/usr/share/icons/hicolor/16x16/apps/krusader_blue.png
/usr/share/icons/hicolor/16x16/apps/krusader_red.png
/usr/share/icons/hicolor/16x16/apps/krusader_root.png
/usr/share/icons/hicolor/16x16/apps/krusader_user.png
/usr/share/icons/hicolor/22x22/apps/krusader_blue.png
/usr/share/icons/hicolor/22x22/apps/krusader_red.png
/usr/share/icons/hicolor/22x22/apps/krusader_root.png
/usr/share/icons/hicolor/22x22/apps/krusader_shield.png
/usr/share/icons/hicolor/22x22/apps/krusader_user.png
/usr/share/icons/hicolor/32x32/apps/krusader_blue.png
/usr/share/icons/hicolor/32x32/apps/krusader_red.png
/usr/share/icons/hicolor/32x32/apps/krusader_root.png
/usr/share/icons/hicolor/32x32/apps/krusader_shield.png
/usr/share/icons/hicolor/32x32/apps/krusader_user.png
/usr/share/icons/hicolor/48x48/apps/krusader_blue.png
/usr/share/icons/hicolor/48x48/apps/krusader_red.png
/usr/share/icons/hicolor/48x48/apps/krusader_root.png
/usr/share/icons/hicolor/48x48/apps/krusader_shield.png
/usr/share/icons/hicolor/48x48/apps/krusader_user.png
/usr/share/icons/hicolor/64x64/apps/krusader_blue.png
/usr/share/icons/hicolor/64x64/apps/krusader_red.png
/usr/share/icons/hicolor/64x64/apps/krusader_root.png
/usr/share/icons/hicolor/64x64/apps/krusader_shield.png
/usr/share/icons/hicolor/64x64/apps/krusader_user.png
/usr/share/krusader/icons/hicolor/16x16/actions/kr_combine.png
/usr/share/krusader/icons/hicolor/16x16/actions/kr_comparedirs.png
/usr/share/krusader/icons/hicolor/16x16/actions/kr_diskusage.png
/usr/share/krusader/icons/hicolor/16x16/actions/kr_mountman.png
/usr/share/krusader/icons/hicolor/16x16/actions/kr_syncbrowse_off.png
/usr/share/krusader/icons/hicolor/16x16/actions/kr_syncbrowse_on.png
/usr/share/krusader/icons/hicolor/16x16/actions/kr_unselect.png
/usr/share/krusader/icons/hicolor/22x22/actions/kr_combine.png
/usr/share/krusader/icons/hicolor/22x22/actions/kr_comparedirs.png
/usr/share/krusader/icons/hicolor/22x22/actions/kr_diskusage.png
/usr/share/krusader/icons/hicolor/22x22/actions/kr_mountman.png
/usr/share/krusader/icons/hicolor/22x22/actions/kr_unselect.png
/usr/share/krusader/icons/hicolor/32x32/actions/kr_combine.png
/usr/share/krusader/icons/hicolor/32x32/actions/kr_comparedirs.png
/usr/share/krusader/icons/hicolor/32x32/actions/kr_diskusage.png
/usr/share/krusader/icons/hicolor/32x32/actions/kr_mountman.png
/usr/share/krusader/icons/hicolor/32x32/actions/kr_unselect.png
/usr/share/krusader/layout.xml
/usr/share/krusader/midnight_commander.color
/usr/share/krusader/splash.png
/usr/share/krusader/total_commander.color
/usr/share/krusader/total_commander.keymap
/usr/share/krusader/total_commander.keymap.info
/usr/share/krusader/useraction_examples.xml
/usr/share/kservices5/iso.protocol
/usr/share/kservices5/krarc.protocol
/usr/share/kxmlgui5/krusader/krusaderlisterui.rc
/usr/share/kxmlgui5/krusader/krusaderui.rc
/usr/share/kxmlgui5/krusader/krviewer.rc
/usr/share/metainfo/org.kde.krusader.appdata.xml
/usr/share/xdg/kio_isorc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/en/krusader/Icon-edit-delete.png
/usr/share/doc/HTML/en/krusader/actionman.png
/usr/share/doc/HTML/en/krusader/advanced-functions.docbook
/usr/share/doc/HTML/en/krusader/archives.docbook
/usr/share/doc/HTML/en/krusader/basic-functions.docbook
/usr/share/doc/HTML/en/krusader/bookmanadd.png
/usr/share/doc/HTML/en/krusader/bookmanedit.png
/usr/share/doc/HTML/en/krusader/bookmarks.docbook
/usr/share/doc/HTML/en/krusader/checksum.docbook
/usr/share/doc/HTML/en/krusader/cmdline.png
/usr/share/doc/HTML/en/krusader/compare.docbook
/usr/share/doc/HTML/en/krusader/configuration-files.docbook
/usr/share/doc/HTML/en/krusader/copyjob.png
/usr/share/doc/HTML/en/krusader/credits-and-license.docbook
/usr/share/doc/HTML/en/krusader/diskusage.docbook
/usr/share/doc/HTML/en/krusader/editors-note.docbook
/usr/share/doc/HTML/en/krusader/faq.docbook
/usr/share/doc/HTML/en/krusader/features.docbook
/usr/share/doc/HTML/en/krusader/fnkeys.png
/usr/share/doc/HTML/en/krusader/glossary.docbook
/usr/share/doc/HTML/en/krusader/help.docbook
/usr/share/doc/HTML/en/krusader/index.cache.bz2
/usr/share/doc/HTML/en/krusader/index.docbook
/usr/share/doc/HTML/en/krusader/installation.docbook
/usr/share/doc/HTML/en/krusader/introduction.docbook
/usr/share/doc/HTML/en/krusader/keyboard-commands.docbook
/usr/share/doc/HTML/en/krusader/kgstartup.png
/usr/share/doc/HTML/en/krusader/konfigurator.docbook
/usr/share/doc/HTML/en/krusader/krusader-tools.docbook
/usr/share/doc/HTML/en/krusader/krusader1.png
/usr/share/doc/HTML/en/krusader/listpanel.png
/usr/share/doc/HTML/en/krusader/locate.docbook
/usr/share/doc/HTML/en/krusader/mainwindow.png
/usr/share/doc/HTML/en/krusader/menu-commands.docbook
/usr/share/doc/HTML/en/krusader/mount.docbook
/usr/share/doc/HTML/en/krusader/mountman.png
/usr/share/doc/HTML/en/krusader/mouse-commands.docbook
/usr/share/doc/HTML/en/krusader/occupied-space.docbook
/usr/share/doc/HTML/en/krusader/profiles.docbook
/usr/share/doc/HTML/en/krusader/release-overview.docbook
/usr/share/doc/HTML/en/krusader/remote-connections.docbook
/usr/share/doc/HTML/en/krusader/search.docbook
/usr/share/doc/HTML/en/krusader/search_advanced.png
/usr/share/doc/HTML/en/krusader/search_general.png
/usr/share/doc/HTML/en/krusader/splitter.docbook
/usr/share/doc/HTML/en/krusader/syncdir.png
/usr/share/doc/HTML/en/krusader/synchronizer.docbook
/usr/share/doc/HTML/en/krusader/tabbed_browsing.png
/usr/share/doc/HTML/en/krusader/terminalEmu.png
/usr/share/doc/HTML/en/krusader/toolbar.png
/usr/share/doc/HTML/en/krusader/user-interface.docbook
/usr/share/doc/HTML/en/krusader/useraction-xml.docbook
/usr/share/doc/HTML/en/krusader/useractions.docbook
/usr/share/doc/HTML/en/krusader/vfs.docbook
/usr/share/doc/HTML/en/krusader/viewer-editor.docbook

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/kio_iso.so
/usr/lib64/qt5/plugins/kio_krarc.so

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/krusader.1
